name: Deploy static site to EC2 (EIC)

on:
  push:
    branches: [ main ]
    paths:
      - "static-website/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Generate ephemeral SSH keypair
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -N "" -f ~/.ssh/ephemeral_key
          echo "PUBKEY=$(cat ~/.ssh/ephemeral_key.pub)" >> $GITHUB_ENV

      - name: Discover instance AZ (needed for EIC)
        id: az
        run: |
          AZ=$(aws ec2 describe-instances --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
               --query "Reservations[0].Instances[0].Placement.AvailabilityZone" --output text)
          echo "AZ=$AZ" >> $GITHUB_OUTPUT

      - name: Push ephemeral public key via EC2 Instance Connect
        run: |
          aws ec2-instance-connect send-ssh-public-key \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}" \
            --availability-zone "${{ steps.az.outputs.AZ }}" \
            --instance-os-user "${{ secrets.EC2_USER }}" \
            --ssh-public-key "$PUBKEY"
        env:
          PUBKEY: ${{ env.PUBKEY }}

      - name: Copy index.html and reload nginx
        run: |
          HOST=$(aws ec2 describe-instances --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
                 --query "Reservations[0].Instances[0].PublicIpAddress" --output text)

          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          # Copy file
          scp -i ~/.ssh/ephemeral_key -o StrictHostKeyChecking=yes \
              static-website/index.html \
              "${{ secrets.EC2_USER }}@${HOST}:/tmp/index.html"

          # Move into place & reload nginx
          ssh -i ~/.ssh/ephemeral_key -o StrictHostKeyChecking=yes \
              "${{ secrets.EC2_USER }}@${HOST}" '
            sudo mkdir -p /var/www/staging
            sudo mv /tmp/index.html /var/www/staging/index.html
            sudo chmod 644 /var/www/staging/index.html
            sudo nginx -t && sudo systemctl reload nginx
          '
