name: Deploy Selected Files to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Disable symlinks (prevents "file name too long" errors)
      - name: Disable symlinks
        run: git config --global core.symlinks false

      # Step 2: Checkout only the files we need
      - name: Checkout only needed files
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            static-website/index.html
            static-website/login.html
            static-website/Static Website Logo update.png
          sparse-checkout-cone-mode: true

      # Step 3: Install AWS CLI
      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Sync selected files to S3
      - name: Sync selected files to S3
        run: |
          aws s3 sync ./static-website s3://andos-reviews-site --delete \
            --exclude "*" \
            --include "index.html" \
            --include "login.html" \
            --include "Static Website Logo update.png"
