name: Deploy static site to EC2

on:
  push:
    branches: [ main ]
    paths:
      - "static-website/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use your EC2 key pair stored in a GitHub secret
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Trust EC2 host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Ensure web root exists
        run: |
          ssh -o StrictHostKeyChecking=yes "${EC2_USER}@${EC2_HOST}" '
            sudo mkdir -p /var/www/staging
          '
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Copy index.html to EC2 and reload nginx
        run: |
          scp -o StrictHostKeyChecking=yes \
              static-website/index.html \
              "${EC2_USER}@${EC2_HOST}:/tmp/index.html"

          ssh -o StrictHostKeyChecking=yes "${EC2_USER}@${EC2_HOST}" '
            sudo mv /tmp/index.html /var/www/staging/index.html
            sudo chmod 644 /var/www/staging/index.html
            sudo nginx -t && sudo systemctl reload nginx
          '
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
