name: Deploy Selected Files to S3

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the full repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history, safer for file copying

      # Step 2: Install AWS CLI
      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 3: Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Copy only the files we want into a deploy folder
      - name: Prepare deploy folder
        run: |
          mkdir deploy
          cp static-website/index.html deploy/
          cp static-website/login.html deploy/
          cp static-website/Static\ Website\ Logo\ update.png deploy/

      # Step 5: Sync deploy folder to S3
      - name: Sync files to S3
        run: |
          aws s3 sync ./deploy s3://andos-reviews-site --delete
