jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only needed files
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure pip is installed
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install AWS CLI
        run: pip install --upgrade awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 1: Still sync files into the bucket
      - name: Sync selected files to S3
        run: |
          aws s3 sync ./static-website s3://andos-reviews-site --delete \
            --exclude "*" \
            --include "index.html" \
            --include "login.html" \
            --include "Static Website Logo update.png"

      # Step 2: Tell EC2 to pull those via SSM
      - name: Trigger SSM DeployStaging on EC2
        run: |
          aws ssm send-command \
            --document-name DeployStaging \
            --instance-ids "${{ secrets.STAGING_INSTANCE_ID }}" \
            --parameters S3URI="s3://andos-reviews-site/" \
            --comment "Deploy staging from GitHub" \
            --query "Command.CommandId" --output text
