name: Deploy Selected Files to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo without checking out files
      - name: Checkout minimal
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          # Do NOT checkout files that may contain symlinks
          path: temp-repo
          # Prevent symlinks from being checked out
          # (we’ll manually copy the files we want)
          
      # Step 2: Copy only the files you need into a clean folder
      - name: Copy selected files
        run: |
          mkdir selected-files
          cp temp-repo/static-website/index.html selected-files/
          cp temp-repo/static-website/login.html selected-files/
          cp temp-repo/static-website/Static\ Website\ Logo\ update.png selected-files/

      # Step 3: Install AWS CLI
      - name: Set up AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 5: Sync selected files to S3
      - name: Sync selected files to S3
        run: |
          aws s3 sync ./selected-files s3://andos-reviews-site --delete
