name: Publish index.html to S3 (manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload index.html to S3 /Productions/
        run: |
          aws s3 cp static-website/index.html \
            s3://andos-reviews-site/Productions/index.html \
            --content-type "text/html; charset=utf-8" \
            --cache-control "no-cache, no-store, must-revalidate"
